JubilifeCity_Condominiums_1F_MapScripts::
	.byte 0

JubilifeCity_Condominiums_1F_EventScript_Man::
	msgbox JubilifeCity_Condominiums_1F_Text_EveryPokemonHasAbility, MSGBOX_NPC
	end

JubilifeCity_Condominiums_1F_EventScript_Woman::
	msgbox JubilifeCity_Condominiums_1F_Text_PokemonStrange, MSGBOX_NPC
	end

JubilifeCity_Condominiums_1F_Text_EveryPokemonHasAbility:
	.string "Every POKéMON has a special ability\n"
	.string "that it can use.$"

JubilifeCity_Condominiums_1F_Text_PokemonStrange:
	.string "POKéMON are such strange creatures.$"

