OreburghCity_House1_MapScripts::
	.byte 0

OreburghCity_House1_EventScript_Man::
	msgbox OreburghCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

OreburghCity_House1_EventScript_Woman::
	msgbox OreburghCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

OreburghCity_House1_Text_TravelingIsWonderful:
	.string "Traveling is wonderful!\p"
	.string "When I was young, I roamed the seas\n"
	.string "and the mountains!$"

OreburghCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "Crawl through some damp grass…\n"
	.string "Climb rocky, rugged mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Wander about in dark caves…\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick…\p"
	.string "It must be fabulous to travel!$"

